Gitlab 15.4 Updates
aws-quickstart/quickstart-eks-gitlab pull request #151
Opened 2022-10-06 16:58 UTC by DarwinJS

*Issue #132 

*Description of changes:*
- Get Gitlab 15 Working

Additional Todos:

- [x] End to end test for 15.x with updated automation
- [ ] Counter-test cipher fix on 14.x and maybe 13.x

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-10-06 17:44 UTC, tlindsay42 requested changes

2022-10-06 17:44 UTC, tlindsay42 commented on .taskcat.yml
> +    QSS3BucketRegion: us-east-1
@troy-ameigh ^^, Darwin implemented this to workaround an issue where the taskcat container can only handle buckets in us-east-1.

@DarwinJS Did you create an issue for this? Didn't see it in the taskcat repo or else I'd tag it in this PR.

2022-10-06 17:44 UTC, tlindsay42 commented on .taskcat.yml
> +    -
Was this intentional? Likely need to remove. ?

2022-10-06 17:44 UTC, tlindsay42 commented on .taskcat.yml
> +      PublicHostedZoneId: Z08828103MVPQNHL7GWYE
Please replace with an override (example: `PublicHostedZoneId: --override--`). Any input parameter value can be overridden via a `.taskcat_overrides.yml` file, but it's best practice to explicitly list override or something to that effect for developer-specific and sensitive values. It's also not best practice to commit live resource IDs.

2022-10-07 10:25 UTC, DarwinJS commented on .taskcat.yml
> +    QSS3BucketRegion: us-east-1
Here you go: https://github.com/aws-ia/taskcat/issues/764

2022-10-07 10:26 UTC, DarwinJS commented on .taskcat.yml
> +    -
Nope and guess what - taskcat linting caught this one!

2022-10-07 19:30 UTC, tlindsay42 commented
/do-e2e-tests

2022-11-03 11:17 UTC, DarwinJS commented
@tlindsay42 - ready for merge when you are.

2022-11-03 14:41 UTC, tlindsay42 commented
/do-e2e-tests

2022-11-03 17:32 UTC, tlindsay42 approved these changes

2022-11-03 17:32 UTC, merged